### ISSUE TITLE
Kerbin has Gilly's description in ScienceDefs.cfg

### ISSUE THREAD

**Issue by help137** [linuxgurugamer/CactEye-2#1]
Kerbin has Gilly's description in the ScienceDefs.cfg file. 

VisualObservationGilly = Gilly is a lumpy rock wandering around the orbit of Eve. Its by far the smallest natural satellite that the Kerbal Astronomical Society has discovered. Due to the large amount of squinting and eye strain associated with its discovery, wearing glasses has now become synonymous with becoming an accomplished Astronomer.
**VisualObservationKerbin** = Gilly is a lumpy rock wandering around the orbit of Eve. Its by far the smallest natural satellite that the Kerbal Astronomical Society has discovered. Due to the large amount of squinting and eye strain associated with its discovery, wearing glasses has now become synonymous with becoming an accomplished Astronomer.

Suggestion for Kerbin:
VisualObservationKerbin = A unique world, Kerbin has flat plains, soaring mountains and wide, blue oceans. Home to the Kerbals, it has just the right conditions to support a vast, seemingly undepletable population of the eager green creatures.

**Comment by linuxgurugamer** [comment]
Thank you, incorporated into upcoming release
