### ISSUE TITLE
The included OPMScienceDefs.cfg patch does not work.

### ISSUE THREAD

**Issue by help137** [linuxgurugamer/CactEye-2#2]
The included OPMScienceDefs.cfg patch does not work (no errors, just does nothing). 

To get it to work change the first code line from:

`@EXPERIMENT_DEFINITION[*]:HAS[#id[CactEyePlanetary]]:NEEDS[OPM]`

to

`@EXPERIMENT_DEFINITION:HAS[#id[CactEyePlanetary]]:NEEDS[OPM]:AFTER[CactEye]`

(Remove the [*], Experiments do not have names)

**Comment by linuxgurugamer** [comment]
Thank you, will be in the imminent release
